from flask import Flask, request, render_template, send_file
from openai import OpenAI
import base64
import os
from dotenv import load_dotenv
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import letter

# --- SETUP ---
load_dotenv()
app = Flask(__name__)
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

UPLOAD_FOLDER = "static/uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# --- HELPERS ---
def encode_image(file):
    return base64.b64encode(file.read()).decode("utf-8")

def save_file(file, filename):
    path = os.path.join(UPLOAD_FOLDER, filename)
    file.seek(0)
    file.save(path)
    return path

def generate_pdf(data, front_path, back_path):
    file_path = "postcard_analysis.pdf"

    doc = SimpleDocTemplate(file_path, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("<b>PostArk Analysis</b>", styles["Title"]))
    elements.append(Spacer(1, 12))

    # Images
    if front_path:
        elements.append(Paragraph("<b>Front Image</b>", styles["Heading2"]))
        elements.append(Image(front_path, width=250, height=150))
        elements.append(Spacer(1, 12))

    if back_path:
        elements.append(Paragraph("<b>Back Image</b>", styles["Heading2"]))
        elements.append(Image(back_path, width=250, height=150))
        elements.append(Spacer(1, 12))

    # Sections
    for key in ["overview", "analysis", "story", "timeline"]:
        if data.get(key):
            elements.append(Paragraph(f"<b>{key.title()}</b>", styles["Heading2"]))
            elements.append(Paragraph(data[key], styles["BodyText"]))
            elements.append(Spacer(1, 12))

    # Footer link
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by PostArk", styles["Italic"]))

    doc.build(elements)
    return file_path

# --- ROUTES ---
@app.route("/", methods=["GET", "POST"])
def index():
    result = None
    front_path = None
    back_path = None

    if request.method == "POST":
        try:
            front = request.files.get("front")
            back = request.files.get("back")

            if not front or not back:
                return render_template("index.html", result={"error": "Upload both images."})

            # Save files
            front_path = save_file(front, "front.jpg")
            back_path = save_file(back, "back.jpg")

            front_img = encode_image(front)
            back_img = encode_image(back)

            response = client.responses.create(
                model="gpt-4.1-mini",
                input=[{
                    "role": "user",
                    "content": [
                        {"type": "input_text", "text": """
Analyze this postcard and return JSON with:
overview, analysis, story, timeline.
"""},
                        {"type": "input_image", "image_url": f"data:image/jpeg;base64,{front_img}"},
                        {"type": "input_image", "image_url": f"data:image/jpeg;base64,{back_img}"}
                    ]
                }]
            )

            text_output = response.output[0].content[0].text

            # Basic parsing fallback
            result = {
                "overview": text_output,
                "analysis": "",
                "story": "",
                "timeline": ""
            }

        except Exception as e:
            result = {"error": str(e)}

    return render_template(
        "index.html",
        result=result,
        front_path=front_path,
        back_path=back_path
    )

@app.route("/download_pdf", methods=["POST"])
def download_pdf():
    data = request.form.get("data")
    front_path = request.form.get("front_path")
    back_path = request.form.get("back_path")

    import json
    data = json.loads(data)

    pdf_path = generate_pdf(data, front_path, back_path)

    return send_file(pdf_path, as_attachment=True)

# --- RUN ---
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)